spring:
  datasource:
    username: postgres
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://jhu-journeroo-postgres.fly.dev:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
