spring:
  datasource:
    username: postgres
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://jhu-journeroo-postgres.fly.dev:5432/postgres
    hikari:
      max-lifetime: 600_000 # 10 minutes
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
