CREATE TABLE IF NOT EXISTS journeys (
    journeyId INT GENERATED BY DEFAULT AS IDENTITY,
    departureTimestamp TIMESTAMP NOT NULL,
    returnTimestamp TIMESTAMP NOT NULL,
    departureStationId INT NOT NULL,
    departureStationName VARCHAR(64) NOT NULL,
    returnStationId INT NOT NULL,
    returnStationName VARCHAR(64) NOT NULL,
    distance INT NOT NULL,
    duration INT NOT NULL
);
